name: API Tests

on:
  push:
    branches:
      - main 
  pull_request:
    paths:
      - 'tests/api/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Maven
      run: sudo apt-get install -y maven

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Start Backend Server
      run: |
        cd backend
        npm install
        nohup node index.js &
        sleep 5

    - name: Run API Tests
      run: |
        cd tests/api
        mvn test
