name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Google Chrome 137
      run: |
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_137.0.6926.99-1_amd64.deb
        sudo dpkg -i google-chrome-stable_137.0.6926.99-1_amd64.deb || sudo apt-get install -f -y

    - name: Install matching ChromeDriver 137.0.6963.41
      run: |
        wget -N https://chromedriver.storage.googleapis.com/137.0.6963.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run UI tests
      working-directory: ./tests/ui
      run: mvn clean test