name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # Remove cache since package.json files are in subdirectories

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Start Backend Server
      working-directory: ./backend
      run: |
        npm start &
        echo $! > ../backend.pid
        sleep 5
        # Verify backend is running
        curl -f http://localhost:3001/items || exit 1

    - name: Start Frontend Server
      working-directory: ./frontend
      run: |
        npm start &
        echo $! > ../frontend.pid
        # Wait for frontend to be ready
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

    - name: Run UI tests
      working-directory: ./tests/ui
      run: mvn clean test

    - name: Stop servers
      if: always()
      run: |
        if [ -f backend.pid ]; then
          kill $(cat backend.pid) || true
          rm backend.pid
        fi
        if [ -f frontend.pid ]; then
          kill $(cat frontend.pid) || true
          rm frontend.pid
        fi